// Generated by gencpp from file beginner_tutorials/String_Modify.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_STRING_MODIFY_H
#define BEGINNER_TUTORIALS_MESSAGE_STRING_MODIFY_H

#include <ros/service_traits.h>


#include <beginner_tutorials/String_ModifyRequest.h>
#include <beginner_tutorials/String_ModifyResponse.h>


namespace beginner_tutorials
{

struct String_Modify
{

typedef String_ModifyRequest Request;
typedef String_ModifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct String_Modify
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::String_Modify > {
  static const char* value()
  {
    return "ce8c0532094f50bab075d6707a3fc45b";
  }

  static const char* value(const ::beginner_tutorials::String_Modify&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::String_Modify > {
  static const char* value()
  {
    return "beginner_tutorials/String_Modify";
  }

  static const char* value(const ::beginner_tutorials::String_Modify&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::String_ModifyRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::String_Modify >
template<>
struct MD5Sum< ::beginner_tutorials::String_ModifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::String_Modify >::value();
  }
  static const char* value(const ::beginner_tutorials::String_ModifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::String_ModifyRequest> should match
// service_traits::DataType< ::beginner_tutorials::String_Modify >
template<>
struct DataType< ::beginner_tutorials::String_ModifyRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::String_Modify >::value();
  }
  static const char* value(const ::beginner_tutorials::String_ModifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::String_ModifyResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::String_Modify >
template<>
struct MD5Sum< ::beginner_tutorials::String_ModifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::String_Modify >::value();
  }
  static const char* value(const ::beginner_tutorials::String_ModifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::String_ModifyResponse> should match
// service_traits::DataType< ::beginner_tutorials::String_Modify >
template<>
struct DataType< ::beginner_tutorials::String_ModifyResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::String_Modify >::value();
  }
  static const char* value(const ::beginner_tutorials::String_ModifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_STRING_MODIFY_H
