/gazebo_ros_control/pid_gains:
right_front_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
right_back_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
left_front_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
left_back_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
head_swivel_joint: {p: 100.0, i: 0.01, d: 10.0}

